### ISSUE TITLE
[BUG] Warning about UTF-8 compatibility

### ISSUE THREAD

**Issue by Nick-Eagles** [LieberInstitute/SPEAQeasyWorkshop2020#2]
In the [acknowledgements section of the vignette](https://github.com/LieberInstitute/SPEAQeasyWorkshop2020/blob/master/vignettes/SPEAQeasyWorkshop2020.Rmd#L296-L297), a couple names of Winter Genomics members contain accented characters, which I have pinpointed as the source of a [warning that the document is not UTF-8 compatible](https://github.com/LieberInstitute/SPEAQeasyWorkshop2020/blob/master/vignettes/SPEAQeasyWorkshop2020.Rmd#L290-L297). I believe the accented characters are actually included in the UTF-8 set though. This warning occurred along with [issue #1](https://github.com/LieberInstitute/SPEAQeasyWorkshop2020/issues/1), so it's hard to tell if this is a critical problem (it is a warning and not error), but I've had a similar "warning" break GHA before on other projects.

**Comment by Nick-Eagles** [comment]
**Update**: the accented characters do indeed cause a fatal error, as seen [here](https://github.com/LieberInstitute/SPEAQeasyWorkshop2020/runs/1551982139#step:21:161). I've removed them for now to diagnose other issues.

**Comment by lcolladotor** [comment]
I think that we can close this issue for now and revisit it later if needed.
